# Generated by Django 6.0.2 on 2026-03-23 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('SALARY_SLIP', 'Salary Slip'), ('PREVIOUS_LEASE', 'Previous Lease Agreement'), ('EMPLOYMENT_LETTER', 'Employment Letter'), ('BANK_STATEMENT', 'Bank Statement'), ('ID_PROOF', 'Government ID Proof'), ('PROPERTY_PAPER', 'Property Ownership Document'), ('TAX_DOC', 'Tax Document/Receipt'), ('OTHER', 'Other Document')], default='OTHER', max_length=50)),
                ('title', models.CharField(help_text='A friendly name for the document', max_length=255)),
                ('file', models.FileField(upload_to='user_docs/%Y/%m/%d/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
