# Generated by Django 5.2.6 on 2026-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_kyc_id_alter_paymentreceipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='contract_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='security_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
