# Generated by Django 5.2.6 on 2026-03-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymentreceipt_contract_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='period_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='period_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
