# Generated by Django 5.2.6 on 2026-03-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_paymentreceipt_period_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='aadhaar_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhaar/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='extracted_id_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/pan/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='verification_score',
            field=models.FloatField(default=0.0),
        ),
    ]
