# Generated by Django 6.0.2 on 2026-03-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_kyc_aadhaar_image_kyc_extracted_id_no_kyc_pan_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KYC',
        ),
    ]
