# Generated by Django 5.2.6 on 2026-03-03 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('property', '0003_property_contract_fee_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text='The monthly anniversary date this feedback is due.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Submission'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired/Ignored')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='contract.contract')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='1 to 5 rating')),
                ('responsiveness_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='1 to 5 rating')),
                ('safety_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='1 to 5 rating')),
                ('vibe_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Neighborhood/Hostel vibe')),
                ('comments', models.TextField(blank=True, help_text='Any issues or highlights this month?')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='feedback.feedbackrequest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_feedbacks', to='property.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
