# Generated by Django 6.0.2 on 2026-03-09 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card')], max_length=20)),
                ('id_number', models.CharField(max_length=100)),
                ('aadhaar_image', models.ImageField(blank=True, null=True, upload_to='kyc/aadhaar/')),
                ('pan_image', models.ImageField(blank=True, null=True, upload_to='kyc/pan/')),
                ('extracted_id_no', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_score', models.FloatField(default=0.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
