# Generated by Django 6.0.2 on 2026-03-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='amenities_list',
            field=models.TextField(blank=True, help_text='Fixtures/furniture list for agreement'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='kyc',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='kyc',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='kyc',
            name='co_owner_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='kyc',
            name='co_owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='kyc',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='kyc',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='kyc',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='kyc',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kyc',
            name='employer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='kyc',
            name='home_state',
            field=models.CharField(blank=True, help_text='For police verification', max_length=100),
        ),
        migrations.AddField(
            model_name='kyc',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='kyc',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='num_occupants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='occupant_names',
            field=models.TextField(blank=True, help_text='Comma-separated names'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='kyc',
            name='ownership_proof',
            field=models.FileField(blank=True, help_text='Title Deed / Sale Deed', null=True, upload_to='kyc/ownership/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='pan_number',
            field=models.CharField(blank=True, help_text='10-char PAN (e.g., ABCDE1234F)', max_length=10),
        ),
        migrations.AddField(
            model_name='kyc',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/photos/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='previous_landlord_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='kyc',
            name='previous_landlord_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='kyc',
            name='property_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='property_size',
            field=models.CharField(blank=True, help_text='e.g., 1200 sq.ft', max_length=50),
        ),
        migrations.AddField(
            model_name='kyc',
            name='property_tax_receipt',
            field=models.FileField(blank=True, help_text='Latest receipt', null=True, upload_to='kyc/tax/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='property_type',
            field=models.CharField(blank=True, help_text='e.g., 2BHK Apartment', max_length=100),
        ),
        migrations.AddField(
            model_name='kyc',
            name='reason_for_moving',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='full_name',
            field=models.CharField(help_text='As on government ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='id_type',
            field=models.CharField(blank=True, choices=[('AADHAAR', 'Aadhaar Card'), ('PASSPORT', 'Passport'), ('VOTER_ID', 'Voter ID'), ('DRIVING_LICENSE', "Driver's License")], max_length=20),
        ),
    ]
