# Generated by Django 6.0.2 on 2026-03-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_kyc_amenities_list_kyc_bank_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='num_occupants',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='occupant_names',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='previous_landlord_contact',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='previous_landlord_name',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='reason_for_moving',
        ),
    ]
