# Generated by Django 6.0.2 on 2026-03-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_kyc_num_occupants_remove_kyc_occupant_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='tenant_type',
            field=models.CharField(choices=[('PROFESSIONAL', 'Working Professional'), ('STUDENT', 'Student')], default='PROFESSIONAL', max_length=20),
        ),
    ]
