# Generated by Django 6.0.2 on 2026-03-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profeature_promembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='ownership_proof',
            field=models.FileField(blank=True, help_text='Electricity Bill (Latest)', null=True, upload_to='kyc/ownership/'),
        ),
    ]
