# Generated by Django 5.2.6 on 2026-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookingrequest_id_alter_bookingrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
