# Generated by Django 5.2.6 on 2026-03-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookingrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='start_date',
            field=models.DateField(blank=True, help_text='Tenancy start date (always 1st of the month)', null=True),
        ),
    ]
