# Generated by Django 5.2.6 on 2026-03-01 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0003_property_contract_fee_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_score', models.FloatField(default=0.0)),
                ('study_score', models.FloatField(default=0.0)),
                ('shopping_score', models.FloatField(default=0.0)),
                ('residential_score', models.FloatField(default=0.0)),
                ('top_vibe', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vibe', to='property.property')),
            ],
        ),
    ]
