# Generated by Django 5.2.6 on 2026-03-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0004_bookingrequest_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('inspection_complete', models.BooleanField(default=False)),
                ('inventory_confirmed', models.BooleanField(default=False)),
                ('utilities_transferred', models.BooleanField(default=False)),
                ('orientation_done', models.BooleanField(default=False)),
                ('keys_handed_over', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='booking.bookingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='e.g., Living Room Walls, Kitchen Sink', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='onboarding/conditions/')),
                ('owner_verified', models.BooleanField(default=True)),
                ('tenant_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_reports', to='onboarding.onboardingprocess')),
            ],
        ),
        migrations.CreateModel(
            name='OrientationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_and_regulations', models.TextField(help_text='Curfew, guest policies, noise rules')),
                ('meal_menu', models.TextField(blank=True, help_text='Weekly menu for PGs/Hostels')),
                ('caretaker_contact', models.CharField(blank=True, max_length=255)),
                ('is_read_by_tenant', models.BooleanField(default=False)),
                ('onboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='onboarding.onboardingprocess')),
            ],
        ),
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='e.g., Study Table, Mattress, Locker Key', max_length=100)),
                ('condition', models.CharField(default='GOOD', max_length=50)),
                ('is_confirmed_by_tenant', models.BooleanField(default=False)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='onboarding.onboardingprocess')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityOrService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('POWER', 'Electricity/Power'), ('WATER', 'Water Supply'), ('GAS', 'Gas Connection'), ('INTERNET', 'Internet/WiFi'), ('MESS', 'Mess/Meal Timings')], max_length=20)),
                ('details', models.TextField(help_text='Instructions, timings, or account details')),
                ('is_transferred_or_ready', models.BooleanField(default=False)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='onboarding.onboardingprocess')),
            ],
        ),
    ]
