# Generated by Django 5.2.6 on 2026-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contract_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of security deposit for contract fee', max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='security_deposit_months',
            field=models.IntegerField(default=2, help_text='Number of months of rent for security deposit'),
        ),
    ]
