# Generated by Django 5.2.6 on 2026-03-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_contract_fee_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='current_occupancy',
            field=models.IntegerField(default=0, help_text='Number of current tenants'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_capacity',
            field=models.IntegerField(default=1, help_text='Total number of tenants this property can handle'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('VILLA', 'Villa'), ('COMMERCIAL', 'Commercial'), ('PLOT', 'Plot'), ('PG', 'Paying Guest')], default='APARTMENT', max_length=20),
        ),
    ]
