# Generated by Django 5.2.6 on 2026-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_current_occupancy_property_total_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('PG', 'Paying Guest')], default='APARTMENT', max_length=20),
        ),
    ]
