# Generated by Django 5.2.6 on 2026-03-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ac_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='List amenities (Lift, Gym, etc.)'),
        ),
        migrations.AddField(
            model_name='property',
            name='availability_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='balconies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bhk_type',
            field=models.CharField(blank=True, choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK+', '4BHK+')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cleaning_frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='food_details',
            field=models.TextField(blank=True, help_text='Specify meals: Breakfast, Lunch, Dinner'),
        ),
        migrations.AddField(
            model_name='property',
            name='food_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('FULLY', 'Fully Furnished'), ('SEMI', 'Semi-Furnished'), ('UNFURNISHED', 'Unfurnished')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('BOYS', 'Boys Only'), ('GIRLS', 'Girls Only'), ('COED', 'Co-ed')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='laundry_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_type',
            field=models.CharField(blank=True, choices=[('COVERED', 'Covered (Basement)'), ('OPEN', 'Open Parking')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rules_restrictions',
            field=models.TextField(blank=True, help_text='Curfew, Guest policy, etc.'),
        ),
        migrations.AddField(
            model_name='property',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='property',
            name='sharing_type',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('QUADRUPLE', 'Quadruple')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
        ),
    ]
