# Generated by Django 5.2.6 on 2026-03-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_ac_available_property_amenities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='food_included',
            new_name='alcohol_allowed',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='availability_date',
            new_name='available_from',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='laundry_available',
            new_name='electricity_included',
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bhk_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cleaning_frequency',
        ),
        migrations.RemoveField(
            model_name='property',
            name='food_details',
        ),
        migrations.RemoveField(
            model_name='property',
            name='maintenance_charges',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rules_restrictions',
        ),
        migrations.AddField(
            model_name='property',
            name='connectivity_info',
            field=models.TextField(blank=True, help_text='Metro/BRTS distance'),
        ),
        migrations.AddField(
            model_name='property',
            name='curfew_time',
            field=models.CharField(default='No Curfew', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='diet_type',
            field=models.CharField(choices=[('VEG', 'Pure Veg'), ('NONVEG', 'Non-Veg Allowed')], default='VEG', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='food_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_biometric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_geyser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_microwave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_refrigerator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_stove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_study_table',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_wardrobe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_washing_machine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_for_professionals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_for_students',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lock_in_period',
            field=models.IntegerField(default=0, help_text='Months'),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_landmarks',
            field=models.TextField(blank=True, help_text='e.g., 500m from College'),
        ),
        migrations.AddField(
            model_name='property',
            name='non_veg_allowed',
            field=models.BooleanField(default=True, help_text='Non-veg cooking allowed'),
        ),
        migrations.AddField(
            model_name='property',
            name='notice_period',
            field=models.IntegerField(default=30, help_text='Days'),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_proof',
            field=models.FileField(blank=True, null=True, upload_to='property/ownership/'),
        ),
        migrations.AddField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='provides_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='provides_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='provides_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, help_text='Flat/Unit Number (Required for Legal Agreement)', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video tour link'),
        ),
        migrations.AddField(
            model_name='property',
            name='visitor_policy',
            field=models.CharField(choices=[('ALLOWED', 'Visitors Allowed'), ('NO', 'No Visitors'), ('DAYTIME', 'Daytime Only'), ('OVERNIGHT', 'Overnight Allowed')], default='ALLOWED', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='water_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_speed',
            field=models.IntegerField(default=0, help_text='Mbps'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='gender_preference',
            field=models.CharField(choices=[('BOYS', 'Boys Only'), ('GIRLS', 'Girls Only'), ('COED', 'Co-ed / Everyone')], default='COED', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('PG', 'PG/Hostel'), ('STUDIO', 'Studio Apartment'), ('BHK1', '1BHK Flat'), ('BHK2', '2BHK Flat'), ('BHK3', '3BHK Flat'), ('SHARED', 'Shared Apartment')], default='BHK2', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='security_deposit_months',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='property',
            name='sharing_type',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('DOUBLE', '2-Sharing'), ('TRIPLE', '3-Sharing'), ('QUADRUPLE', '4-Sharing')], max_length=20, null=True),
        ),
    ]
