# Generated by Django 5.2.6 on 2026-03-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_rename_food_included_property_alcohol_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='laundry_service',
            field=models.BooleanField(default=False, help_text='Is laundry service provided?'),
        ),
    ]
