# Generated by Django 5.2.6 on 2026-03-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_laundry_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment / Flat'), ('PG', 'PG / Hostel')], default='APARTMENT', max_length=20),
        ),
    ]
