# Generated by Django 5.2.6 on 2026-03-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='ownership_proof',
        ),
        migrations.AddField(
            model_name='property',
            name='electricity_bill',
            field=models.FileField(blank=True, null=True, upload_to='property/verification/electricity/'),
        ),
        migrations.AddField(
            model_name='property',
            name='extra_amenities',
            field=models.TextField(blank=True, help_text='Additional amenities not mentioned above (comma separated)'),
        ),
        migrations.AddField(
            model_name='property',
            name='extra_house_rules',
            field=models.TextField(blank=True, help_text='Additional rules or terms for tenants'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_tax_slip',
            field=models.FileField(blank=True, null=True, upload_to='property/verification/tax/'),
        ),
    ]
