# Generated by Django 5.2.6 on 2026-03-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_remove_property_ownership_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bed_count',
            field=models.PositiveIntegerField(default=1, help_text='Specific for PG/Hostel sharing count'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_coffee_maker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_ergonomic_chair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_induction_plate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_toaster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_workspace_desk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
