# Generated by Django 5.2.6 on 2026-03-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_property_bed_count_property_has_coffee_maker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_carbon_monoxide_alarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_emergency_exit_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_fire_extinguisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_first_aid_kit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_smoke_alarm',
            field=models.BooleanField(default=False),
        ),
    ]
