# Generated by Django 5.2.6 on 2026-02-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promembership',
            name='tier',
            field=models.CharField(choices=[('PRO', 'BrosDen Pro'), ('GOLD', 'BrosDen Gold')], default='PRO', max_length=50),
        ),
    ]
